### ISSUE TITLE
Allow registry trios that are not IDE examples

### ISSUE THREAD

**Issue by joshsunshine** [penrose/penrose#1034]
**Is your feature request related to a problem? Please describe.**
Some of the examples in our registry are not appropriate for public display in the examples tab of the IDE. The registry should allow certain trios to be excluded from the registry. 

**Describe the solution you'd like**
Add a flag to `registry.json` for each trio that allows the registry author to exclude a particular trio from the IDE example list.

**Comment by wodeni** [comment]
Maybe separate registries?

**Comment by cmumatt** [comment]
> Maybe separate registries?

Looks like only a small subset needs to be hidden on the IDE.  May not be worth creating a separate registry just for a few differences, and it seems like there would be an advantage to one central registry.  In the future we could centrally control trio applicability based on the flags attached to the trio.  I.e, which are benchmarked, displayed in the IDE, etc.

**Comment by cmumatt** [comment]
@rhit-chois3 coded the fix for this issue, but his testing is blocked by PR #1037.  The reason: on `main`, the IDE's `registry.json` is sourced from GitHub rather than locally.  Once PR #1037 is merged, `registry.json` will be sourced locally and we can test and merge this fix.  Another option is to merge the fix into main without testing, let GitHub update, and then test.  Since this isn't urgent, I'm not suggesting the alternate path.

**Comment by maxkrieger** [comment]
I think we should have separate trio files altogether

**Comment by samestep** [comment]
Resolved by #1212.
