### ISSUE TITLE
When a file is updated in the IDE by Roger, automatically trigger a recompile

### ISSUE THREAD

**Issue by cmumatt** [penrose/penrose#1048]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When a file is updated in the IDE by Roger, automatically trigger a recompile

**Describe alternatives you've considered**
Currently it is necessary to manually click "Compile" after Roger updates a file.

**Comment by YonahGoldberg** [comment]
I'll try to get this done. I thought it was as easy as adding `compileDiagram` calls to the [updatedFile](https://github.com/YonahGoldberg/penrose/blob/ce807462b463d11d47cd267de58a1f46f8b142ab/packages/editor/src/App.tsx#L200-L220) call back in the editor's App.txt. However, I have to save my changes twice in order for the diagram to update. I think it might have to do with the workspace state not being updated in time, since there is a compile refresh animation on the first change even though the changes aren't applied.

**Comment by samestep** [comment]
@YonahGoldberg that sounds great! In general thinking harder about how we do state management is probably a fruitful direction, as it directly pertains to the web workers stuff we're trying to do: #1207
