### ISSUE TITLE
Setting sizes in Substance

### ISSUE THREAD

**Issue by Vtec234** [penrose/penrose#1057]
**Is your feature request related to a problem? Please describe.**

Sometimes I would like to control the sizes of things per-diagram (i.e. per-substance), and per-entity. I might have a `type FooBox` in my DSL, and some default styling for `FooBox`es in Style. However, is it possible to then create a bunch of `FooBox`s in the Substance and then control their sizes from there? Something like
```penrose
FooBox A,B,C
SetWidth(A, 20)
SetWidth(B, 30)
SetWidth(C, 40)
```

**Describe the solution you'd like**

An ability to do the above or something like it.

**Describe alternatives you've considered**

At first glance it doesn't seem possible to control sizes per-entity in this way in the Style program either. I could create a bunch of fake types like `FooBoxA, FooBoxB, FooBoxC` and set their widths which seems very clunky.

**Additional context**

I am working on a DSL for commutative diagrams, with the goal of integrating some Penrose SVGs within the Lean 4 theorem prover. The commutative diagrams contain boxes which must have the correct width to fit a pretty-printed term of Lean's type theory.

I'm not sure if this is the right place to ask - if I should email or go onto some chat platform instead, let me know!

**Comment by samestep** [comment]
Hey @Vtec234, thanks for reaching out! Exciting to hear that Lean folks are using Penrose :)

This question gets at a longstanding design tension we've had, essentially about whether to allow numbers in Substance; see also #949 for another recent discussion about this. Currently we're targeting a use case where Substance programs are written only by humans and not machines, but that starts to break down in many cases where the _rest_ of the Penrose system is still useful, but the Substance language kind of gets in the way. More broadly, @wodeni and I have been talking about the idea of improving the Penrose API to provide a richer way to programmatically provide generated Substance, but nothing around this has materialized yet.

---

Anyway, that aside, for your specific use case, @keenancrane pointed out that you could do something like this in Style:
```
FooBox `A` {
   override `A`.icon.width = 20
}
```
That is, leave the type as `FooBox` for all your objects (so you don't need to modify your Domain file), but use Style's ability to match against specific Substance object names.

Does this help with your use case? My guess is that it probably doesn't, since you mentioned that you're pretty-printing terms to put in these boxes, so I'm guessing that these numbers are programmatically generated so you can't hardcode them into a Style program?

Assuming that's the case, could you go into a bit more detail about these pretty-printed terms? Are they, e.g., LaTeX strings or SVGs (both of which Penrose allows embedding directly)? If yes then I think there's a way to just use Penrose to get their bounding boxes programmatically from within Style. But from the way you phrased it, it sounds like maybe you're generating them in some other form, passing just the dimensions to Penrose to generate the boxes, and then adding the terms themselves to the image afterward as a postprocessing step?

---

The above are all just workarounds that don't address your direct question of allowing numbers in Substance. I think we're potentially open to that idea, but we'd need to have some design discussion in the team; regardless, it would be great to hear more details about your specific use case to inform that discussion.

**Comment by Vtec234** [comment]
> Does this help with your use case? My guess is that it probably doesn't, since you mentioned that you're pretty-printing terms to put in these boxes, so I'm guessing that these numbers are programmatically generated so you can't hardcode them into a Style program?

It does, thanks a bunch! I didn't know it was possible to select by label. You're right that I can't hardcode it beforehand, but I can just append some extra code to the style program every time I generate a new instance, so I think it should work.

> But from the way you phrased it, it sounds like maybe you're generating them in some other form, passing just the dimensions to Penrose to generate the boxes, and then adding the terms themselves to the image afterward as a postprocessing step?

That's right. The pretty-printed terms are DOM nodes of known width with onClick handlers and so on, so unfortunately I have to hack around a bit by positioning them over the SVG using `absolute` coordinates (SVG's `foreignObject` did not work well when I tried it as it applies transforms to the node, although that wasn't on a Penrose-generated SVG).

>  it would be great to hear more details about your specific use case to inform that discussion.

Btw, my Penrose code is [here](https://github.com/Vtec234/npm-widget/tree/39486f1e554ead1d36e6cb212a6523726106f6e0/widget/src/penrose). As you can see, the DSL includes layout predicates like "point arrow vertically downwards". In an ideal world I could just say "please draw four vertices" and the system would optimize that into a square, bu my attempts to encode the conventions of how people draw commutative diagrams into a full optimization heuristic quickly grew computationally infeasible.

**Comment by Vtec234** [comment]
>  If you're not already using it, please feel free to give it a try!

I already was :) It is very cool.

> Would love to see your early attempts at it! Graph layout is something we'd like to tackle for a while. Especially curious about the "optimization heuristic quickly grew computationally infeasible" part.

I unfortunately deleted them, but I can try to recall two things I ran into.

1. In the current code, specifying that `A` and `B` are connected by a horizontal arrow (to draw `A → B`) makes the Style program [*assign* the position](https://github.com/Vtec234/npm-widget/blob/39486f1e554ead1d36e6cb212a6523726106f6e0/widget/src/penrose/commutative.sty#L77) of `B` to be a function of `A.center` with nothing to optimize. Earlier on, I was trying `override B.center = (?, A.center[1])` and `ensure A.center[0] < B.center[0]` and similar clauses for every other predicate, together with the "objects repel each other" optimization target. This would work but would take a few seconds (I want the diagrams to show up quickly in interactive use), and depending on the starting conditions the diagram wouldn't always be sensible — sometimes all objects ended up in a tangled mess at the same position. I suppose the art here is in writing down constraints that are not only correct but also efficient to optimize. Maybe `B.center = A.center + (?, 0)` is another option with one fewer constraint.
2. In general, given their variety, drawing "sensible" commutative diagrams given just the objects and arrows but not the "arrow goes to right", "curve this arrow left", predicates that I am using seems really difficult. As far as I know, no existing software can do it. There are lots of implicit conventions that are perfectly natural for humans but don't seem easily encodable.

> Saw in the Style comment that arrow styling is a TODO item. Happy to investigate ways to customize arrows from our end, as it seems to be a pretty generalizable feature (something like [quiver](https://q.uiver.app/) perhaps).

This would be amazing! Quiver-style arrows are exactly what I am looking for. In fact, I initially tried just embedding Quiver but their drawing code is really tied-in with the editor code and uses global state which I didn't really feel like library-fying.
