### ISSUE TITLE
Provide non-Vim keyboard shortcut to recompile

### ISSUE THREAD

**Issue by samestep** [penrose/penrose#1272]
Compare/contrast with #1046.

**Comment by Dsm0** [comment]
monaco-editor doesn't have a great interface for custom keybindings but will try to do this with [addCommand](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IStandaloneCodeEditor.html#addCommand) in [EditorPane.tsx](https://github.com/penrose/penrose/blob/main/packages/components/src/editing/EditorPane.tsx)

**Comment by Dsm0** [comment]
https://github.com/penrose/penrose/tree/recompile-shortcut 
recompiles with "ctrl+enter"
Chose "ctrl+enter" for the binding because almost everything else I tried was either caught by the browser first, or simply didn't give any feedback. Keys that didn't work include single letters and digits. Why ctrl+enter _does_ work, I have no idea.

I'm not sure what's intercepting the events, because they work fine in the [editor playground](https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-listening-to-key-events). We'd definitely need to resolve this issue if we were to add more bindings.

**Comment by samestep** [comment]
@Dsm0 ah nice! Very weird but I guess that's how it goes... could you put that in a PR?

**Comment by Dsm0** [comment]
Update: all the `monaco.KeyMod`  and `monaco.CtrlCmd` constants are just standard keycodes, so we could really do everything with `.onKeyDown()` as long as we only care about keybindings active while the editor is focused. 

Global keybindings would still probably be fiddly though.
