### ISSUE TITLE
Improve random sampling by using updated rng for computations

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#161]
Currently, all computations use the same `compRng`, whose updated state is not stored or passed around. This means that resampling a diagram will not resample parameters that depend on `compRng` (e.g. the points of a sampled function). 

To fix this, we should generalize computations to take a `StdGen` as input, return an updated `StdGen`, use that state when applying computations in `GenOptProblem`, and store that state in the `State` type. (We could use the `rng` that is already stored there.)

I think doing this will make our resampling dramatically more interesting and effective.

**Comment by wodeni** [comment]
Resolved in 4827c03. 

## Summary of the solution:

* `CompFn` is now defined as:  `type CompFnOn   a = [ArgVal a] -> StdGen -> (ArgVal a, StdGen)`
* Existing computation functions are ported with `ConstCompFn` type and a `constComp :: ConstCompFn -> CompFn` wrapper can be used 
* The `rng` field in the `State` is used to evaluate computation. 
* `evalTranslation` returns the lastest `rng`, but in some cases we do not update the state with this new generater. 
  * Specifically, within a single optimization session (a single sample), we do _not_ update the state because that would give us new random samples (e.g. different looking curves) at every step of the optimization. 

Closing the issue now.

**Comment by hypotext** [comment]
Thanks! Looks good overall. I left some minor comments on the commit. 

Can you also update the [Style compiler docs](https://github.com/penrose/penrose/wiki/How-the-Style-compiler-works) to incorporate the treatment of randomness? Namely, it would be good to document (at a high level) *when* the rng state is threaded through (e.g. in a fold) and *when* we intentionally discard the rng state/history.

**Comment by hypotext** [comment]
Fixed by @wodeni
