### ISSUE TITLE
Optimization should be cancellable via Websocket

### ISSUE THREAD

**Issue by maxkrieger** [penrose/penrose#186]
If the optimizer gets stuck, or the user gets impatient, there should be a way for the IDE and other clients to cancel the *autostep* optimization via websocket packet. Note that this shouldn't be destructive, it should just turn autostep off.

Right now, toggling autostep releases the frontend for further manipulation, but the backend continues sending new optimized frames to the browser.

**Comment by maxkrieger** [comment]
@wodeni How difficult would this be?

**Comment by maxkrieger** [comment]
Nevermind, I just realized this is already possible when toggling Autostep!

**Comment by wodeni** [comment]
@maxkrieger and I discussed two possible solutions:

1. Since Haskell WebSocket lib doesn't support non-blocking reads, we can fork another reader thread for each client and buffer incoming command. When we optimize with `autostep` on, we would peek at the buffer and see if there is any pending command in it before proceeding to `stepAndSend`.
Idea came from this issue: https://github.com/jaspervdj/websockets/issues/101

2. By @maxkrieger: we send "heartbeat" packets at each step and require the client to respond either with or without new commands. The cost is that we add another roundtrip each time we exchange the heartbeat packet and response. This strategy could be significantly simpler to implement since solution 1 will require some serious concurrent work, which could be tricky.

**Comment by maxkrieger** [comment]
Another possible solution: eliminate server-side autostep altogether. If autostep is enabled on the frontend, the frontend will automatically send a step packet every time it receives an updated frame from the server.
This is mostly a refined and ultra-simplified version of the heartbeat idea, with presumably the same perf.

**Comment by maxkrieger** [comment]
Should be solved by #236 assuming `stepUntilConvergence` can be killed automatically by the backend if it stalls.
