### ISSUE TITLE
USAGE.txt: openFile: does not exist

### ISSUE THREAD

**Issue by yurivict** [penrose/penrose#320]
Versiion 0.1.1.1 fails:
```
src/Penrose/ShadowMain.hs:59:15: error:
    * Exception when trying to run compile-time code:
        USAGE.txt: openFile: does not exist (No such file or directory)
      Code: template-haskell-2.14.0.0:Language.Haskell.TH.Quote.quoteExp
              docoptFile "USAGE.txt"
    * In the quasi-quotation: [docoptFile|USAGE.txt|]
```

Source is taken from Hackage.

FreeBSD 12

**Comment by maxkrieger** [comment]
I think the Hackage version is well out of date. We really don't have
"official" releases yet, you may have better luck cloning master.

@wodeni we should consider actual releases/versioning as one of the steps
towards ramp-up!

**Comment by arrowd** [comment]
@yurivict This problem is on our side. Take a look at other Haskell ports that install data. They have additional knob `xxx_DATADIR_VAR` and `post-install` target. It seems, you have to install `USAGE.txt` at least.

@maxkrieger Releases allows us, packagers, to conveniently grab source tarball using our machinery. So yes, having a release (preferably, on Hackage) will be much appreciated.

**Comment by maxkrieger** [comment]
@arrowd Penrose in its current state is likely difficult to package from source because it requires an independent "frontend" component that depends on nodejs/npm.
A binary version of Penrose will need the static frontend bundle and a lightweight static server built in.

**Comment by yurivict** [comment]
I've updated the port to the latest master, and the problem went away.
