### ISSUE TITLE
Improve labeling in general

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#368]
Currently, labels are placed in a very ad-hoc manner, by applying `repel`/`atDist`/etc objectives and constraints in a very brittle way in the Style program. The goal is to come up with a general, fast, flexible, label-specific layout strategy that also works with the rest of the diagram.

It is easy to get started with some small existing Penrose diagrams, and working to improve their labeling (e.g. one label near the end of a vector's arrow).

Maybe we can apply an approach like from this paper: ["Specifying Label Layout Styles by Example"](http://vis.berkeley.edu/papers/labellay/labellay.pdf) (especially the above's "properties of good label layouts")

Also check out the Vega team's [work on label placement](https://pen-rose.slack.com/archives/C2QTUUKFF/p1601063485005600).

**Comment by joshpoll** [comment]
For posterity, the Vega label placement paper referred to here is ["Fast and Flexible Overlap Detection
for Chart Labeling with Occupancy Bitmap"](https://idl.cs.washington.edu/files/2021-FastLabels-VIS.pdf), which is used in Vega since version 5.16: https://vega.github.io/vega/docs/transforms/label/.
