### ISSUE TITLE
Strings in Style get interpreted as TeX by default

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#393]
In substance, a TeX string is specified via

```
label xHat $\hat{x}$
```

whereas in Style writing

```
A.text = Text {
      string: "$\hat{x}$"
}
```

produces a literal string $\hat{x}$; in order for this string to be rendered as TeX one has to drop the dollar signs:

```
A.text = Text {
      string: "\hat{x}"
}
```

This seems to violate the "principle of least surprise," i.e., that (i) string specification looks different across different languages, and (ii) _adding_ dollar signs prevents TeX from getting rendered properly.

There may also be cases where one expects plain text, and finds that the string has been interpreted as TeX instead.  E.g., suppose that

```
A.text = Text {
      string: "my_var"
}
```

is meant to label a programmatic variable name (say, for illustrating a piece of code).  This string will get rendered with a subscript v following the y…

**Comment by samestep** [comment]
> Change the style syntax so strings are escaped with $.

I realized recently that this actually doesn't quite work: there are various other types of string literals in Style, which do not get interpreted as TeX. Examples include:

- `"rgb"` for `sampleColor`
- `fontSize`
- `stroke`/`style`/`arrowheadStyle`/`strokeStyle`
- `"open"`/`"closed"` for `arc`/`pathFromPoints`
- `strokeDashArray`
- `data`/`viewBox` for `PathString`

Also, for `Text`'s `string` property, simply replacing double quotes with dollar signs would still be awkward because currently backslashes need to be escaped.

**Comment by keenancrane** [comment]
A similar issue on the Substance side is raised in #721.

**Comment by wodeni** [comment]
Now that we have `Text` that is different from `Equation` (#740). Closing this issue
