### ISSUE TITLE
Naming of color-related fields for graphical primitives

### ISSUE THREAD

**Issue by GeometryCollective** [penrose/penrose#415]
Currently, there are shapes (such as `Circle`) that have fields named `color`.  Three problems here:

- `color` is a name conflict with the `color` type (confusing!)
- the word `color` on its own is ambiguous (is it the fill color? stroke color? etc.)
- this field name is different than the name used in SVG

**Proposal 1:** just adopt the names used in SVG.  E.g., for `Circle` we should have `fill` and `stroke`.

Note, by the way, that SVG calls these fields `fill` and `stoke`, not `fillColor` and `strokeColor`.  One good reason for that, perhaps, is that the _fill/stroke need not be a solid color!_ For instance, they might be a pattern, etc., (and SVG has support for this).

**Proposal 2:** If we want all the functionality of SVG to eventually be exposed in Penrose, fields like `fill` and `stroke` should take a value whose type is a _supertype_ of `color` (and which also includes, say, `pattern`).

See [here](http://tutorials.jenkov.com/svg/fill-patterns.html) for an example of a fill pattern in SVG.

**Comment by wodeni** [comment]
I'd prefer `fillColor` and `strokeColor`

**Comment by cmumatt** [comment]
While working issue #704, observed the following different uses of fill, stroke, strokeColor, and color properties that should probably be made consistent as they can be confusing.

- Image
   - No fill paint property
   - strokeColor is called stroke and set to string value: “none."  (this precedes the no-paint functionality)
- Text
   - strokeColor is called stroke and set to string value: “none."  (this precedes the no-paint functionality)
- Line:
  - color, which is usually the fill property, is used for stroke paint here.  Inconsistent.
  - strokeColor is called stroke and set to string value: “none."  (this precedes the no-paint functionality)
- Arrow
  - No stroke paint property.
- Path
  - color is called fill, which is inconsistent with all the other shapes
  - color, which is usually the fill property, is used for stroke paint here.  Inconsistent.

As to the question above about what to call these, I would lean toward fill or fillPaint due to these properties not always being a color in the SVG spec.  For stroke, stroke or strokePaint seem reasonable.

If you guys want me to work on this one, just assign it to me and I'll adapt it to whichever naming seems most logical.  The most time-consuming part will likely be updating the examples.

**Comment by samestep** [comment]
I just checked: it was.

**Comment by keenancrane** [comment]
One thing to note: although we took care of the renaming, the values that this field can take are still just flat colors.  SVG also [allows the "color" to be a pattern](https://css-tricks.com/almanac/properties/f/fill/).

**Comment by samestep** [comment]
@keenancrane That seems like a separate issue (more about the syntax of the Style language than about the naming of our shape properties); could you create a new issue for that if one doesn't already exist?
