### ISSUE TITLE
NaN Error in optimization of even simple Venn diagrams

### ISSUE THREAD

**Issue by JonathanAldrich** [penrose/penrose#583]
**Describe the bug**
I was trying to create a Venn diagram and got the following error:

`Uncaught (in promise) Error: NaN reached in optimization energy or gradient norm!
    at I (index.esm.js:43444)
    at Zf (index.esm.js:43450)
    at Pf (index.esm.js:43104)
    at WT (index.esm.js:82330)
    at App.tsx:131
    at App.tsx:155
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at i (asyncToGenerator.js:3)
I @ index.esm.js:43444
Zf @ index.esm.js:43450
Pf @ index.esm.js:43104
WT @ index.esm.js:82330
(anonymous) @ App.tsx:131
(anonymous) @ App.tsx:155
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
i @ asyncToGenerator.js:3
a @ asyncToGenerator.js:25
Promise.then (async)
i @ asyncToGenerator.js:13
a @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ App.tsx:153
je @ react-dom.production.min.js:52
qe @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
yi @ react-dom.production.min.js:100
bi @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Oe @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Si @ react-dom.production.min.js:105
$t @ react-dom.production.min.js:75
Xt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
jA @ react-dom.production.min.js:122
Me @ react-dom.production.min.js:292
Wt @ react-dom.production.min.js:73`

**To Reproduce**
I was working on panels.penrose.ink.  I pasted in setTheory.dsl and venn.sty from the main branch of penrose (commit dbf710646bcaad9f0e3142388ae4759ca6b3a740, though note that panels.penrose.ink may not be up to this commit).

Here's the substance that I was using:

```
Set declarative, functional, logic

IsSubset(logic, declarative)
IsSubset(functional, declarative)


AutoLabel All
```

Steps to reproduce the behavior: Clicking "compile" produces the error above.

**Expected behavior**
I expect to get a Venn diagram

**Additional context**
It works for smaller set names, but with the longer labels in the sample program even this Venn diagram fails in optimization.

**Comment by hypotext** [comment]
Interesting. I wonder if the problem is harder to solve due to the longer label names. Will take some digging to figure out if this is the problem.

**Comment by cmumatt** [comment]
Thanks for reporting this problem!

Good news: this problem is fixed, and the example no longer NaNs.

Steps to demonstrate in production:
1. Go to: https://penrose.cs.cmu.edu/try/
2. Click `Examples`-->`tree-venn`
3. Click the `Tree.sub` tab and paste in the Substance program above
4. Click "Compile" and observe output similar to the below.

![image](https://user-images.githubusercontent.com/22134678/176790080-366766c8-6ef9-467d-ac39-28287631e3e3.png)

Looking slightly broader, labels that render at a width that occupy a significant percentage of canvas width can still lead to slow optimization and/or inability to solve for all constraints.  This can be seen pretty easily by (a) reducing the size of the canvas, (b) increasing the label font size, or (c) making the object labels extremely long (to be clear, _much_ longer than in this example!).  In these cases, the optimizer does not NaN, but it can still perform slowly and/or fail to solve for all constraints.
