### ISSUE TITLE
Visualize more functions (injection, bijection, etc.) in the Cartesian style

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#63]
[Intro task for Dor]

We have surjections, injections, and bijections all working in the "discrete" set theory style. But we only have surjections working in the Cartesian style (see the [example page](https://github.com/penrose/penrose/wiki/Examples)). 

Can you get injections and bijections working in the Cartesian style, and add a new function type of your own?

Note: I will merge the `surjection` branch first; then you can start working on this.

**Comment by hypotext** [comment]
> As I understand it, I should define similar computing functions to those of surjection at the file: Computation.hs and then simply to use them in a dedicated style program?

Yes, you'll need to write and register computations to sample the various kinds of functions, then write new Substance and Style programs for them. You should also extend the parser to match on the type of function (surjection/injection/etc) as currently it just matches on Map (which is too general).

**Comment by dormaayan** [comment]
@hypotext By extending the parser to match on the type of function do you mean to extend Substance (i.e `Surjection f` as in your comments)? Is there doc anywhere on how to extend Substance, if not I'll simply understand how to do that from the code

**Comment by wodeni** [comment]
@dormaayan the doc, unfortunately, does not cover it in great details partly because the process will not be as structured as adding a shape. In general, you need to do the following to get some custom syntax you add to work (ordered in my preferred way):

- modify the AST to reflect your grammar
- add parser functions using Megaparsec (e.g. if you want to add a new type of statement, start by adding another option to `stmt` function)
- go into one of the `proc*` functions in the same file and add the semantic analysis/"code generation" logic there. Continuing the example, you would go to `procStmt` and add custom code there, depending on what you are adding. 
- Modify Runtime, Server etc to get the whole system running. 
- If you changed anything that would affect Style (for now just `SubType`), you need to make some changes to Style as well.

This is super high-level because I haven't thought too much about this specific feature yet.

**Comment by dormaayan** [comment]
@hypotext : We have 2 options for substance syntax here:

1. Declare a new object like: `Surjection f A B`

2. Working on maps: `Map f A B` and in a new line: `Surjection f` (On the same way that intersect \ non intersect is working)

Personally the second syntax make more sense to me. However, I think that we can't use it until we will have the `where` syntax in style. What do you think?

**Comment by hypotext** [comment]
The second one makes more sense in the near future, after we work out more of the Style dynamic semantics. The first one should be relatively easy to implement (will intro you to extending the parser) and should allow you to distinguish between Surjection/Injection/Bijection in Substance. So, I'd say implement the first one for now.
