### ISSUE TITLE
Design and implement standard API for graphical primitives

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#75]
This issue lays a principled foundation for our graphics and optimization framework.

Propose answers to the following questions:

1. From the perspective of optimization, what's the model of a shape? What are all the properties and operations that shapes support? What are the types of the properties and operations? Do all shapes support them, or only certain ones? What is the hierarchy of shapes?
2. What's the interface at the language level? How do Style programs (e.g. objectives, constraints, computation, and shape attributes) use or refer to these properties and operations? 
3. How do we implement the API and (quickly) compute the queries that need to be computed? See issue #22 for more details on implementing signed distance.

Here's an initial list of operations/properties we might want to support: center, distance, length, width, location, beginning, end, area, boundary length, boundary curve, bounding box, margin.

We've already started formalizing some shape APIs and properties as typeclasses, record attributes, and getter/setters (using strings) in the [Shapes](https://github.com/penrose/penrose/blob/master/src/Shapes.hs) module. We'd like it to be more systematic and thorough.

In terms of methodology, it would be better to start with a small (non-exhaustive) API and implement it, then test and iterate end-to-end to a larger API, rather than doing all the design work at once, then all the implementation at once.

Related work: Most of the related work is in physical simulation. What other well-designed optimization-focused APIs for graphical primitives are there, if any? Maybe look at OpenGL, snap.svg, and CSS.

**Comment by wodeni** [comment]
To start the design of this, we should first figure out __a list of spacial queries needed to write most of the objectives and constraints__ (by "queries" I not only refer to boolean tests such as "do this circle and square intersect", but also "how far is the point from this pentagon".  Here are some that I can think of immediately:

* Tangency
* Containment
* Intersection
* Overlap
* Distance

The motivation for doing so is: before implementing a particular representation of the geometries (e.g. level-set representation + signed distance functions, or bounding volume hierarchy), it's better to think about what operations and queries we will do on them.

Feel free to add more to the list!

**Comment by wodeni** [comment]
From 06/07/18 graphics meeting, we sketched a couple of components to be implemented for this API

# Hierarchy of shape representation
- BBox
- __BVH of levelset__
- Analytical form
# Construction of the representations
# Example: general versions of objectives and constraints 
## `overlapping`

**Comment by lilyshellhammer** [comment]
##Overlapping Pseudocode

```Haskell
overlaps Bbox a, Bbox b
if (a.Left < b.Right AND a.Right > b.Left OR...
      return 0
else
    return(dist a.center, b.center)

overlaps BBoxNode a BboxNode b
check overlap
if (a is a leaf node and b is a leaf node)
     if they still overlap
         return (levelSetCheck(a, b))
else
     recurse over tree to get to leaf nodes
```

###Questions
- How to divide up shape into squares? It is easy to find edges of box since we are working in a 2D grid, but how do we do this efficiently? Divide in half every time and loop to find edges?
- We need to calculate Level Set before BVH, do we do that in a constructor function or similar?
- How do we work with pixels in Haskell?

**Comment by lilyshellhammer** [comment]
# Intro
This doc specifies 
- Types that are used in the General Graphics API and pseudocode to generate them
- Functions and a description of the objectives/constraints they satisfy 
- Example uses
- Questions, things to be figured out, etc
---
# Types
```Haskell
Shape
      { ... own components ..., 
      Bbox, 
      Tree (limit to certain shapes?), 
      LevelSet
      }

LevelSet {
      Grid ,    -- 2D with values of signed distance
      Length,
      Width,
      Origin { x, y }, -- x, y of upper left hand corner
      Center { x, y } -- keeps track of center w.r.t page (necessary? 
              -- should instead keep track of center w.r.t grid?)
     }

BBox {
     R, -- Right, left, top, bottom, center 
     OR
     UR point, LL point { x, y }
     Center { x, y }
     ****Question: Should BBox store LevelSet?
     } 

BBoxNode {  --Still need help sorting this one out
    BBox,
    ChildrenNodes,
    IsLeaf
    }
```
## Type Generation
### Level Set/SDF Pseudocode, Fast Sweeping Method: (For 2D but can define this for 3D)
- Get from user or other method - boolean values of what is inside and what is outside
   - can be determined by equation or imported image
- Set boundary line (between inside and out) to 0, all else dummy value
- Find nearest values to 0 spots and calc dist
- For amount of sweeps
  *  for x
    *  for y   (For 3D loop through Z)
      *  sweep across and update values
Each sweep comes from a different direction:  (For 3D need to loop 8 combos to account for z+-1)
  * ULtoLR
  * LLtoUR
  * LRtoUL
  * URtoLL 

### Fast Sweeping Method Literature/Information
- [The Fast Sweeping Method of Eikonal
Equations and Its Parallelism ](https://pdfs.semanticscholar.org/14c2/818b53f8455326cb7f1ca662c9e6472a7fbb.pdf)
- [Fluid Simulation - Section 6.2 Level Sets](https://www.cs.ubc.ca/~rbridson/fluidsimulation/fluids_notes.pdf)
- [Computational Study of Fast Methods for the Eikonal Equation](http://www4.ncsu.edu/~gremaud/sweepnew.pdf)

### Can get pixels of an image through:
[JuicyPixel](https://hackage.haskell.org/package/JuicyPixels) "lightweight library in Haskell allows load and save images in various formats"
[repa](https://hackage.haskell.org/package/repa) "“REgular PArallel arrays”, not specifically tied to image processing, but it's the standard choice when you want to perform calculations on a large collection of numeric data in parallel in Haskell"
[Friday](https://hackage.haskell.org/package/friday) "powerful and new ... allows to manipulate images and has a good collection of operations already coded for you (like edge detection, cropping, filtering, etc.)...similar to repa's operations"
[Gloss](https://hackage.haskell.org/package/gloss)"gloss describes itself as “Painless 2D vector graphics, animations and simulations”... uses OpenGL under the hood."

### BVH Pseudocode (2D but can define this for 3D)
- Find outermost boundary of level set
  - The idea so far: iterate through grid and find max and min x and max and min y
  - Too inefficient?
- Save as Root
- divide in two, find max and min x and max and min y, store in Left and Right Children
- mark Leafs when you reach (certain threshold)

---
# Functions
## 'Overlaps' Function
This function enforces two general shapes overlapping
Example: Circle overlaps with circle
### Pseudocode:
- if bounding boxes don't intersect - return distance of centers
- else create BVH and check if overlapping occurs
- if yes, that means smallest BV overlap but not necessarily shape
- check level set overlap of those overlapping nodes

```Haskell
overlaps Bbox a, Bbox b
if !(a.Left < b.Right AND a.Right > b.Left OR...
      return(dist a.center, b.center)
else 
      -- overlaps BboxNode a BBoxNode b Tree(root)

overlaps BBoxNode a BboxNode b     --TODO: FIGURE OUT
if !(a.Left < b.Right AND a.Right > b.Left OR...
      if (a is a leaf node and b is a leaf node)
          return (overlaps a.levelset b.levelset) 
         -- (***Question: we can't go back to parent to access level set how do we call this?)
     else
     -- return (recurse over tree to get to leaf nodes)

overlaps LevelSet a LevelSet b
forall a.grid[x,y] <= 1
    if b.grid[x,y] <=1
         return 0
return dist(a.center, b.center) - Epislon
```
---
## 'Contains' Function
This function enforces one shape is contained inside another (a contains b)
Example: Circle contains its label
### Pseudocode:
- If bounding box of a does not contain bounding box of b, return distance between centers
- If it does, check level sets within bounding boxes
- If any inside point on b is on an outside point of a, it isn't contained
  - TO DO: Figure out how to move shape correctly toward where it needs to be   
*****Question (for Katherine probably): How do we make the shape bigger via function's return value? How is that implemented currently?

```Haskell
Contains BBox a BBox b
    if ! ( a.L > b. L .... )
        return dist( a.center, b.center) - Epsilon
   else
       return Contains LevelSet a LevelSet b

Contains LevelSet a LevelSet b          
    forall ( b.grid[ x,y ] <= 0 )
          if ( a.grid[ x,y ] > 0 )
               return ( sqrt ( x,y - b.center) ^2 + (b.center - a.center) ^2 ) 
      -- this returns vector from the point outside of the circle to the 
      --center of the other circle. Think pythagorean theorem with points as
      -- center a, center b, point that is not contained
     ***Question: Are there cases where this won't work?
      -- We could also find all points outside, move them toward far edge of other shape
     return 0
```
---
## 'Intersect' Function
This function enforces two shapes/two curves/one shape and one curve intersect
PROBLEM: We need to define intersection better. It isn't simply overlapping because overlapping can equal containment, but this is explicitly overlapping without containment. 
Example: Check that a label don't intersect the edge of a shape but is either inside or outside the shape
Example: Check that two lines intersect
### Pseudocode:
- if Line or Arrow, calculate using pattern matching function
- else call function on level set
- if 0 on one overlaps with 0 on other, intersect. 
****Question: Do we want 0 on 0 or one object to pass through both negative and positive on other
(aka implying more than just tangency) 
- for non overlap
    - if this happens, repel from the intersecting point
    ****Question: Should we see all places where they intersect and store those and then repel from all or work one by one?
- for overlap
   - move centers toward each other?? TODO: Figure out how to make shapes intersect

```Haskell
intersect Line a Line b  --since these are common and very few others
-- will be pattern matched and will use default, define for Line/Arrow
-- easy definition

intersect Arrow a Arrow b
-- easy definition

intersect BBox a BBox b
if !( a.R > b.R ..... )
     intersect a.LevelSet b.LevelSet
else
    return dist( a.center, b.center) - Epsilon

intersect LevelSet a LevelSet b
    forall ( b.grid[ x,y ] == 0 )
        if ( a[ x,y ] == 0 )
            return 0
    return --move centers ? TODO: FIGURE OUT

-- For non intersecting is easier
noIntersection A B
-- similar to above, different minimization returned
intersect LevelSet a LevelSet B
    forall ( b.grid[ x,y ] == 0 )
        if ( a[ x,y ] == 0 )
            -- "repel" :  TODO: Figure out explicit equations
            -- b moves in direction ( x,y - b.center )
            -- a moves in direction ( x,y - a.center ) 
    return 0
```
---
# Questions (pulled from ****Questions in above text)
1. How do we store data that isn't redundant so that we can call Level Set function from BBox or BBoxNode? 
2. How do we make a containing shape bigger via function's return value? How is that implemented currently?
3. Do we want to simply check for 0 on 0 (one border intersects iwth another at one or more points) or do we want to see if one object PASSES THROUGH both negative and positive on other
(aka implying more than only touching edges)?
4. For moving non-contained points inward: should we store ALL places where they intersect then repel from all or work one by one?
