### ISSUE TITLE
Implement Revised Substance & DSLL

### ISSUE THREAD

**Issue by dormaayan** [penrose/penrose#95]
Implement the following according to the design paper:

- [x] Adjust the DSLL Grammar to the paper books
- [x] DSLL subtypes - grammar
- [x] DSLL subtypes - semantic checking
- [x] Substance Binding
- [x] Substance Equality - Grammar
- [x] Substance Equality - type checking
- [x] Loose the order of statements in the DSLL

New:

- [x] Substance deconstructors - grammar
- [x] Substance deconstructors - type checking
- [x] DSLL Prelude (value) declarations
- [ ] Lists and tuples as built-in generic types that are available to any .dsl file

**Comment by dormaayan** [comment]
@hypotext 
In the paper, we defined the deconstructors like that:
`x := D`
Means that they can appear just on the right side of the binding.
However, I see examples in the paper where you use them also in the left side of the binding.
Is that updated, do we want to support them in both sides of the binding?

**Comment by hypotext** [comment]
Which examples are you referring to for the left side of the binding?

**Comment by dormaayan** [comment]
<img width="896" alt="image" src="https://user-images.githubusercontent.com/19957447/45256100-b08b8a00-b35f-11e8-80da-8b36dec7f898.png">

**Comment by hypotext** [comment]
I think the examples I wrote there have unclear semantics. You can ignore them and go ahead with just implementing deconstructors on the right side. 

As a general clarification, here is an example of our use case for value deconstructors:

A Substance program like

```
Function f : A -> B
x \in Dom(f)
```

desugars to:

```
Interval A, B
Function f := MkFunction(A, B)
Real x
In(x, f.domain)
```

And the Style program would have a selector like this:

```
Function g
where g := MkFunction(X, Y); In(p, g.domain)
with Interval X, Y; Real p
```

Note that Substance needs to allow nested/anonymous expressions now like `In(x, f.domain)`. Otherwise we need to bind a new name in Substance `Interval C := f.domain` which would mess up the matching because we wouldn't know that `Interval C` is the same as `Interval B`.

**Comment by hypotext** [comment]
Actually I wonder if value deconstructors should have an evaluation semantics:

`In(x, f.domain)` evaluates to `In(x, A)` in Substance. This would be easier for Style to work with and seems like it would be intuitive to the Substance user.

**Comment by dormaayan** [comment]
That seems reasonable, but that's already supported, right?

**Comment by hypotext** [comment]
What are you referring to by "that"? I believe Substance already allows nested/anon expressions, but Substance has no evaluation semantics. 

It would be helpful to add the evaluation semantics but I don't think it's 100% necessary. The Style writer can infer that "g.domain" refers to "X" (so, we rely on the Style user to do evaluation in their head).

**Comment by dormaayan** [comment]
All done except of lists & built in generic types.
Moved work on them to #173
